### ISSUE TITLE
Prevent different users from using the same name

### ISSUE THREAD

**Issue by PizieDust** [robur-coop/mollymawk#42]
Currently multiple accounts can have the exact same name. We require the email to be unique but not the name. 
This can be problematic given that the `domain` used by albatross is the name of the account.

**Comment by PizieDust** [comment]
What about using the users `uuid` for domain purposes? This can be a quick fix in this case. 
But I assume the other frontends (grafana), may not like the `uuid` values (if it's displayed somewhere in the UI?)

**Comment by hannesm** [comment]
For now, esp. since we've a running albatross with existing setup (and there's no UUID prefix for the unikernels), and the question about where such a mapping (user name and uuid) should be persisted (if needed) -- see https://github.com/robur-coop/albatross/issues/173 -- I'd prefer to check that the user name is unique.

**Comment by PizieDust** [comment]
Thank you for the additional context on the albatross issue. I totally agree it's a bit more complex to decide. I think we can easily just check the names and prevent duplicate ones for the time being.
